-- {{ config(
--     materialized = 'incremental',
--     unique_key = 'id',
--     full_refresh = false,
--     tags = ['defillama']
-- ) }}

-- WITH pool_base AS (

-- {% for item in range(75) %}
-- (
-- SELECT
--     pool_id,
--     protocol,
--     symbol,
--     ethereum.streamline.udf_api(
--         'GET',CONCAT('https://yields.llama.fi/chart/',pool_id),{},{}
--     ) AS read,
--     SYSDATE() AS _inserted_timestamp
-- FROM (
--     SELECT 
--         pool AS pool_id,
--         project AS protocol,
--         symbol,
--         row_num
--     FROM {{ ref('bronze__defillama_api_pools_20230209_131432') }}
--     WHERE row_num BETWEEN {{ item * 150 + 1 }} AND {{ (item + 1) * 150}}
--     )
-- {% if is_incremental() %}
-- WHERE pool_id NOT IN (
--     SELECT
--         pool_id
--     FROM (
--         SELECT 
--             DISTINCT pool_id,
--             MAX(timestamp::DATE) AS max_timestamp
--         FROM {{ this }}
--         GROUP BY 1
--         HAVING CURRENT_DATE = max_timestamp
--     )
-- )
-- {% endif %}
-- ) {% if not loop.last %}
-- UNION ALL
-- {% endif %}
-- {% endfor %}
-- )

-- SELECT
--     pool_id,
--     protocol,
--     symbol,
--     TO_TIMESTAMP(VALUE:timestamp) AS timestamp,
--     VALUE:tvlUsd::INTEGER AS tvl_usd,
--     VALUE:apy::INTEGER AS apy,
--     VALUE:apyBase::INTEGER AS apy_base,
--     VALUE:apyReward::INTEGER AS apy_reward,
--     VALUE:apybase7d::INTEGER AS apy_base_7d,
--     VALUE:il7d::INTEGER AS il_7d,
--     _inserted_timestamp,
--     CONCAT(pool_id,'-',timestamp) AS id
-- FROM pool_base,
--     LATERAL FLATTEN (input=> read:data:data) 