version: 2

sources:
  - name: bronze_streamline
    database: streamline
    schema: "{{ 'external' if target.database == 'EXTERNAL' else 'external_dev' }}"
    tables:
      - name: bitquery
      - name: oklink
      - name: artemis
      - name: defillama_protocol_historical
      - name: valuations_parquet
      - name: defillama_stablecoin_metrics
      - name: defillama_protocols
      - name: defillama_perp_metrics
  - name: tokenflow_eth
    database: flipside_prod_db
    schema: tokenflow_eth
    tables:
      - name: blocks
      - name: calls
      - name: events
      - name: state_diffs
      - name: storage_diffs
      - name: storage_reads
      - name: tokens_allowance_diffs
      - name: tokens_balance_diffs
      - name: tokens_metadata
      - name: transactions
  - name: crosschain_silver
    database: crosschain
    schema: silver
    tables:
      - name: apis_keys
  - name: crosschain_core
    database: crosschain
    schema: core
    tables:
      - name: dim_dates
  - name: crosschain_defi
    database: crosschain
    schema: defi
    tables:
      - name: ez_bridge_activity
  - name: ethereum_silver
    database: ethereum
    schema: silver
    tables:
      - name: nft_transfers
  - name: starknet_snapshot
    database: tokenflow
    schema: starknet
    tables:
      - name: blocks
      - name: events
      - name: messages
      - name: traces
      - name: transactions
      - name: l1_blocks
      - name: l1_contracts
      - name: l1_messages
      - name: l1_storage_diffs
  - name: flashbots
    database: streamline
    schema: flashbots
    tables:
      - name: mev
      - name: protect
  - name: layerzero
    database: external
    schema: layerzero
    tables:
      - name: transactions
  - name: external_bronze
    database: external
    schema: bronze
    tables:
      - name: farcaster_blocks
      - name: farcaster_casts
      - name: farcaster_fids
      - name: farcaster_fnames
      - name: farcaster_links
      - name: farcaster_signers
      - name: farcaster_storage
      - name: farcaster_reactions
      - name: farcaster_user_data
      - name: farcaster_verifications
      - name: farcaster_channel_follows
      - name: farcaster_profile_with_addresses
      - name: farcaster_warpcast_power_users
      - name: aptos_shinam
  - name: avalanche_share
    database: ava_labs_share
    schema: primary
    tables:
      - name: c_blocks
      - name: c_messages
      - name: c_transactions
      - name: c_internal_transactions
      - name: c_receipts
      - name: data_dictionary
      - name: p_blocks
      - name: p_transactions
      - name: utxos
      - name: vertices
      - name: x_blocks
      - name: x_transactions