version: 2

sources:
  - name: tokenflow_starknet_l1_data
    database: tokenflow_starknet
    schema: l1_data
    tables:
      - name: blocks
      - name: contracts
      - name: messages
      - name: storage_diffs
  - name: tokenflow_starknet_decoded
    database: tokenflow_starknet
    schema: decoded
    tables:
      - name: blocks
      - name: events
      - name: messages
      - name: traces
      - name: transactions
  - name: tokenflow_eth
    database: flipside_prod_db
    schema: tokenflow_eth
    tables:
      - name: blocks
      - name: calls
      - name: events
      - name: state_diffs
      - name: storage_diffs
      - name: storage_reads
      - name: tokens_allowance_diffs
      - name: tokens_balance_diffs
      - name: tokens_metadata
      - name: transactions
  - name: crosschain_silver
    database: crosschain
    schema: silver
    tables:
      - name: apis_keys
  - name: ethereum_silver
    database: ethereum
    schema: silver
    tables:
      - name: nft_transfers
  